version: '3.8'
services:
  book-store-db:
    container_name: book-store-db
    image: mongo:5.0.9
    ports:
      - '27017:27017'
    volumes:
      - type: bind
        source: ./mongo-data
        target: /data/db
  message-broker:
    container_name: message-broker
    image: rabbitmq:3.10-management-alpine
    ports:
      - '5672:5672'
      - '15672:15672'
volumes:
  mongo-data:
