service: lc-sold-notifier

frameworkVersion: '2'


provider:
  name: aws
  runtime: nodejs12.x
  lambdaHashingVersion: 20201221

functions:
  hello:
    handler: handler.sold
    events:
      - http:
          path: /sold
          method: POST
          cors: true

plugins: 
  - serverless-offline
